//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tinkwell.Firmwareless.Cloud.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tinkwell.Firmwareless.Cloud.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----BEGIN RSA PRIVATE KEY-----
        ///MIIEowIBAAKCAQEA7SHq3oFqX4PrFv422x6Vh3ibrFBd+3dTrFwHYTDbQm9XtidV
        ///7qfyxmPVeIHblJQY2pMMEYhx5Q1KBVDv6IxIaivYNjDuHYfzLJNHwYbxOLgPZLBm
        ///jewAoVGVG0C7vNIeMNmOM+eOJ0RsuIE1Vae9wS7ATDijBUDYkCsCtksYfQqPRxiR
        ///5vkVGcE9iRpGecxvxhcAOySdmBKmz539KT+g7ZuaDI4b7m32bCRjUxW1HtmpRmud
        ///Gffj0RLuOHeKmVm3n7DO2qZjK/r15JTgkhBTJ9zWT8TKY0/XT5jPCWOr7xC2g/dZ
        ///TNCmw4OQZKaEV0g2YBX37aXawDXQX64G4ItrwQIDAQABAoIBAAqvaUVu2gu4YCE2
        ///zq/JLR5THXSox56OrgsJhJDPe+AxyZqDVqU8rr0ozEdnVpOKqHBxvGzH0+LPc/y3
        ///iaMjB+cc10It3aggAAgL3oMs1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string development_only_private_key {
            get {
                return ResourceManager.GetString("development_only_private_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----BEGIN PUBLIC KEY-----
        ///MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA7SHq3oFqX4PrFv422x6V
        ///h3ibrFBd+3dTrFwHYTDbQm9XtidV7qfyxmPVeIHblJQY2pMMEYhx5Q1KBVDv6IxI
        ///aivYNjDuHYfzLJNHwYbxOLgPZLBmjewAoVGVG0C7vNIeMNmOM+eOJ0RsuIE1Vae9
        ///wS7ATDijBUDYkCsCtksYfQqPRxiR5vkVGcE9iRpGecxvxhcAOySdmBKmz539KT+g
        ///7ZuaDI4b7m32bCRjUxW1HtmpRmudGffj0RLuOHeKmVm3n7DO2qZjK/r15JTgkhBT
        ///J9zWT8TKY0/XT5jPCWOr7xC2g/dZTNCmw4OQZKaEV0g2YBX37aXawDXQX64G4Itr
        ///wQIDAQAB
        ///-----END PUBLIC KEY-----
        ///.
        /// </summary>
        internal static string development_only_public_key {
            get {
                return ResourceManager.GetString("development_only_public_key", resourceCulture);
            }
        }
    }
}
