@Tinkwell.Firmwareless.PublicRepository_HostAddress = http://localhost:5165
@AdminApiKey = ak_kGcswOK1BE6J9U3Ya-DVB5lyqJ7-OFhv
@HubApiKey = ak_FIDPQwZbHEWLH1G6UQGyMir7BKV33-YY

@VendorId = def663bd-779c-4d86-a673-545838cf6173
@UserApiKey = ak_oOCDA0Uye0CekRtYb_V-eJRXdBxTSGob
@ProductId = aed5836b-d6ec-41b2-8b0b-8e17b3125305

### Step 0: check connectivity
GET {{Tinkwell.Firmwareless.PublicRepository_HostAddress}}/status

### Step 1: create a new vendor
POST {{Tinkwell.Firmwareless.PublicRepository_HostAddress}}/api/v1/keys
X-Api-Key: {{AdminApiKey}}
Content-Type: application/json

{
  "name": "Test Vendor",
  "notes": ""
}

### Step 1: create a new vendor
POST {{Tinkwell.Firmwareless.PublicRepository_HostAddress}}/api/v1/vendors
X-Api-Key: {{AdminApiKey}}
Content-Type: application/json

{
  "name": "Test Vendor",
  "notes": ""
}

### Step 1b: list vendors
GET {{Tinkwell.Firmwareless.PublicRepository_HostAddress}}/api/v1/vendors
X-Api-Key: {{AdminApiKey}}

### Step 2: create a new API key for that vendor
POST {{Tinkwell.Firmwareless.PublicRepository_HostAddress}}/api/v1/keys
X-Api-Key: {{AdminApiKey}}
Content-Type: application/json

{
  "vendorId": "{{VendorId}}",
  "name": "Test",
  "role": "User",
  "daysValid": 30,
  "scopes": ["product.create", "product.read", "product.update", "firmware.create", "firmware.read", "firmware.update"]
}

### Step 3: create a new product
POST {{Tinkwell.Firmwareless.PublicRepository_HostAddress}}/api/v1/products
X-Api-Key: {{UserApiKey}}
Content-Type: application/json

{
  "vendorId": "{{VendorId}}",
  "name": "Test Product",
  "model": "Test Model",
  "status": 1
}

### Step 4: check the created product
GET {{Tinkwell.Firmwareless.PublicRepository_HostAddress}}/api/v1/products
X-Api-Key: {{UserApiKey}}

### Step 5: create a new firmware for that product
POST {{Tinkwell.Firmwareless.PublicRepository_HostAddress}}/api/v1/firmwares
X-Api-Key: {{UserApiKey}}
Content-Type: application/json

{
  "productId": "{{ProductId}}",
  "version": "1.5.7",
  "compatibility": "any",
  "type": "Firmlet",
  "status": "Release",
  "author": "Adriano Repetti",
  "copyright": "Adriano",
  "releaseNotesUrl": "https://example.com/notes",  
  "fileBase64": "UEsDBBQAAAAIAGy8E1vDVMtfZgAAAI8AAAANAAAAZmlybXdhcmUuanNvbqvmUlBQcs1LTMpJ9S3NKckMyShKTUxRslJIS8wpTtVByIYkZuY4J+bkYJFyTyxKSkxPdc7PyUlNLsnMz0NR45yfW5CZkwgSD83LLCkGSkYDxYEyiSkpuiXl+XrlicW5SkChWK5aAFBLAwQUAAAACAAOXA9bDSvY3zkAAAA4AAAADAAAAGFkZC10d28ud2FzbWNILM5lZGBgYGRnTGCqr2esZ2ZiZGDnYmRLTEkJKc9nYODiZGRnUGBQYMziZuBiyUvMTWViBmoAAFBLAQIUABQAAAAIAGy8E1vDVMtfZgAAAI8AAAANAAAAAAAAAAAAAACAAQAAAABmaXJtd2FyZS5qc29uUEsBAhQAFAAAAAgADlwPWw0r2N85AAAAOAAAAAwAAAAAAAAAAAAAALaBkQAAAGFkZC10d28ud2FzbVBLBQYAAAAAAgACAHUAAAD0AAAAAAA="
}

### Step 6: list available firmwares
GET {{Tinkwell.Firmwareless.PublicRepository_HostAddress}}/api/v1/firmwares
X-Api-Key: {{UserApiKey}}

### Step 7: download the compiled firmware
POST {{Tinkwell.Firmwareless.PublicRepository_HostAddress}}/api/v1/firmwares/download
X-Api-Key: {{HubApiKey}}
Content-Type: application/json

{
  "vendorId": "{{VendorId}}",
  "productId": "{{ProductId}}",
  "type": "Firmlet",
  "hardwareVersion": "1.0",
  "hardwareArchitecture": "linux"
}
